;;;; SPDX-License-Identifier: bsd-2-clause
;;;; src/matrix-id.lisp
;;;; Generated by dps-meta. Do not hand-edit.
;;;; Re-generate: uses: denzuko/dps-meta@v1
;;;;
;;;; net.matrix identity constants.  Single point of change for namespace rescope.

(defpackage #:mlisp.identity
(:use #:cl)
(:export #:+organisation+
#:+application+
#:+role+
#:+version+
#:label-string))

(in-package #:mlisp.identity)

(defconstant +organisation+ "daplanet"
"net.matrix.organisation value.")

(defconstant +application+ "mlisp"
"net.matrix.application value.")

(defconstant +role+ "list-manager"
"net.matrix.role value.")

(defconstant +version+ "0.9.0"
"Semver string — must match meta.version git config.")

(defun label-string (key value)
"Return a net.matrix OCI label string: 'namespace.KEY=VALUE'."
(format nil "net.matrix.~A=~A" key value))
